# Generated by Django 4.1.7 on 2023-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=40)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
